homework_08/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

homework_08/settings/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from django.views.generic import TemplateView

import blog.views

urlpatterns = [
        path('admin/', admin.site.urls),
        path('', blog.views.post_list, name='post_list'),
        path('blog/', include('blog.urls', namespace='blog')),
        # path('', TemplateView.as_view(template_name='index.html')),
        # path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
            path('__debug__/', include("debug_toolbar.urls")),
    )

homework_08/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Переопределенный менеджер постов с PUBLISHED статусом
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    # Выбор статуса (черновик/опубликовано)
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            related_name='blog_posts',
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
            max_length=2,
            choices=Status.choices,
            default=Status.DRAFT
    )

    objects = models.Manager()  # менеджер, применяемый по умолчанию в DJango
    published = PublishedManager()  # мой менеджер, можно переопределить

    # Похоже, indexes ... не хочет работать с sqlite, или почему-то (ХЗ)
    class Meta:
        ordering = ['-publish']
        indexes = [
                models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

homework_08/blog/views.py
from django.shortcuts import render
from .models import Post
from django.http import Http404


# Create your views here.

def post_list(request):
    posts = Post.published.select_related("author").all()
    # posts = Post.published.all()
    return render(
            request,
            'blog/post/list.html',
            {'posts': posts}
    )


def post_detail(request, id):
    try:
        post = Post.published.select_related("author").get(id=id)
    except Post.DoesNotExist:
        raise Http404('Post does not exist')
    return render(
            request,
            'blog/post/detail.html',
            {'post': post}
    )

homework_08/blog/templates/blog/post/detail.html
{% extends "base.html" %}
{% block title %} DetailView: {{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <div>
        <a href='{% url 'post_list' %}'
        > Вернуться к списку постов</a>
    </div>
{% endblock %}

homework_08/blog/templates/blog/post/list.html
{% extends "base.html" %}
{% block title %} ListView {% endblock %}
{% block content %}
    <h1>Изучаем Django</h1>
    {% for post in posts %}
        <h2>
            <a href="{% url 'blog:post_detail' post.id %}">
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% endblock %}

homework_08/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>Мой блог</h2>
    <p>Пробуем Django.</p>
</div>
</body>
</html>

homework_08/templates/common/footer-common.html
<div>
  <a href="{% url 'list' %}">Back to index</a>
</div>