graduate_work/products/urls.py
from django.contrib import admin
from django.urls import path
from .views import products, basket_add, basket_remove, product_detail

app_name = 'products'

urlpatterns = [
    path('', products, name='products'),
    path('product/<int:id>/<slug:slug>/', product_detail, name='product_detail'),  #
    path('category/<int:category_id>/', products, name='category'),
    path('page/<int:page>/', products, name='page'),
    path('basket/add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

graduate_work/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import index, products
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

graduate_work/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import login, register, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

graduate_work/products/models.py
from django.db import models
from django.urls import reverse

from users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='название')
    slug = models.SlugField(max_length=254, unique=True)
    description = models.TextField(blank=True, verbose_name='описание')
    image = models.ImageField(
        upload_to="category",
        null=True,
        blank=True,
        default="static/vendor/img/categories/category_default.jpg",
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name

    #
    def get_absolute_url(self):
        return reverse('products:category',
                       args=[self.id])


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name='название')
    slug = models.SlugField(max_length=200)  #
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)  #
    description = models.TextField(blank=True, verbose_name='описание')
    short_description = models.CharField(max_length=64, blank=True, verbose_name='краткое описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='количество')
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    #
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']  #
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'{self.name} | {self.category.name}'

    def get_absolute_url(self):
        return reverse('products:product_detail',
                       args=[self.id, self.slug])


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

graduate_work/products/forms.py
from django import forms
from products.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = {
            "category",
            # "sub_category",
            "name",
            "description",
            # "stock",
            "price",
            # "featured",
            # "image_url",
            "image",
            # "sku"
        }

graduate_work/products/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from products.models import Product, ProductCategory, Basket


def index(request):
    context = {
        'title': 'Store',
    }
    return render(request, 'products/index.html', context)


# products_list
def products(request, category_id=None, page=1):
    context = {
        'title': 'Каталог',
        'categories': ProductCategory.objects.all(),
    }
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()
    paginator = Paginator(products, 3)
    products_paginator = paginator.page(page)
    context.update({'products': products_paginator})
    return render(request, 'products/products.html', context)


# product_detail
def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)

    return render(request,
                  'products/product_details.html',
                  {'product': product})


@login_required
def basket_add(request, product_id):
    current_page = request.META.get('HTTP_REFERER')

    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)
    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)

        return HttpResponseRedirect(current_page)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

        return HttpResponseRedirect(current_page)


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

graduate_work/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Drones Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:products' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {#--------------#}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i
                                class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}{% endblock %}

<!-- Footer -->
{% block footer %}{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<!-- FontAwesome script -->
<script src="/static/vendor/fontawesome/fontawesome-icons.js" crossorigin="anonymous"></script>

</body>

</html>

graduate_work/products/templates/products/basket.html
{% if baskets %}
    <div class="col-lg-5">
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.short_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                        <span class="text-muted">{{ basket.quantity }} шт.</span>
                        <span class="text-muted">{{ basket.sum }} руб.</span>
                        <span class="text-muted">
                            <a href="{% url 'products:basket_add' basket.product.id %}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-plus"></i>
                            </a>
                            <a href="{% url 'products:basket_remove' basket.id %}" style="text-decoration: none; color: gray;">
                                <i class="far fa-trash-alt"></i>
                            </a>
                </span>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ total_sum }} руб.</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    </div>
{% else %}
    <h4 class="mt-3 mb-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

graduate_work/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static "css/index.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Drones Store</h1>
                    <p>
                        Создание шаблона для маркетплейса.
                        Основная тема: Проработка моделей товаров, Авторизация / регистрация,
                        Корзина (модель и отображение).
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:products' %}">
                            Перейти к каталогу
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

graduate_work/products/templates/products/product_details.html
{% extends "products/base.html" %}
{% load static %}

{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}"/>
{% endblock %}

{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
    </div>
    {#-----Описание товара------#}
    <section class="section">
        <div class="container">
            <div class="columns is-multiline">
                <div class="column is-6 is-offset-1">
                    <figure class="image">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </figure>
                </div>
                <div class="column is-4">
                    <p class="title has-text-primary is-size-5-mobile">{{ product.name }}</p>
                    <p class="is-size-5 is-size-6-mobile has-text-weight-bold">{{ product.price }} руб.</p>

                    {% if product.quantity > 0 %}
                        <p class="has-text-success is-size-6-mobile">Доступно к заказу</p>
                    {% else %}
                        <p class="has-text-danger is-size-6-mobile">Временно отсутствует</p>
                    {% endif %}
                    {##}
                    <hr>
                    <p class="is-size-6 is-size-7-mobile">Категория:
                        <a href="{{ product.category.get_absolute_url }}">
                            {{ product.category }}
                        </a>
                    </p>
                    <hr/>
                </div>

                <div class="column is-12">
                    <div class="divider has-text-primary">Описание</div>
                    <p>{{ product.description | linebreaksbr }}</p>
                </div>
            </div>
        </div>
    </section>



    {#    #}
{% endblock %}

graduate_work/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static "css/products.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Store</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}"
                           class="list-group-item">{{ category.name }}
                        </a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="/media/{{ product.image }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'products:product_detail' product.id product.slug %}">{{ product.name }}</a>
{#                                        <a href="#">{{ product.name }}</a>#}

                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.short_description }}</p>
                                </div>

                                <div class="card-footer text-center">
                                    <a href="{% url 'products:basket_add' product.id %}">
                                        <button type="button" class="btn btn-outline-success">
                                            Отправить в корзину
                                        </button>
                                    </a>

                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_previous %} {% url 'products:page' products.previous_page_number %} {% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">
                                Предыдущая</a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'products:page' page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_next %} {% url 'products:page' products.next_page_number %} {% else %} # {% endif %}">
                                Следующая</a>
                        </li>
                    </ul>
                </nav>

            </div>

        </div>

    </div>

{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
    <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2024</p>
{% endblock %}